---
openapi: 3.0.0
info:
  title: API Endpoints
  description: |
  version: 1.0.0

servers:
  - url: "https://test-seepass-api.seedao.tech/"
    description: "dev env for the API"
paths:
  "/users":
    get:
      summary: Completions
      tags:
        - 🔌 API
      description: Creates a model response for the given chat conversation.
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        '200':
          description: returns a chat completion object
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
          format: email
      required:
        - id
        - username
        - email
